// TypesFromSerializers CacheKey e5c9d433c169b060c1ea4a5b8a89c818
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface User {
  id: number
  createdAt: string | Date
  emailAddress: string
  updatedAt: string | Date
}
